### ISSUE TITLE
what we have to pass in request_url

### ISSUE THREAD

**Issue by akshaybhagwat76** [mdemblani/twitter-client#2]
Can we pass Consumer Secret (API Secret) in this URL and Why there Callback.html

**Comment by mdemblani** [comment]
The whole idea of having a client-side implementation of Login with twitter is that, you donot want to perform redirects from your application to Twitter and back to your application. This is especially help-full, if you are developing a SPA _(Single Page Application)._

Since the twitter API supports OAuth1.0 Login Flow, on a successful, login, it will directly send a request to your server on the callback url that you had mentioned while registering your application with Twitter. The **callback.html**, is a dummy end-point, whose sole purpose is to handover the controller back _(by closing the currently open iframe)_ to the main javascript _(parent/caller)_ that had initially opened the iframe for the login process.

It would not be recommended to pass the Consumer Secret on the client, but rather pass the token you obtain from the twitter-login script to your server and use it over in your sever code along with the consumer secret.

**Comment by mdemblani** [comment]
Also, the request_url, is an endpoint in your application, which when called, would communicate with the twitter api on the server to obtain an oauth_token. You don't need to pass anything specific to the end-point, or you may wish to pass in some identification information about the website from which the request_url is being called. You are completely free to create the url as you like. The reason for doing this to protect the consumer_secret token that you have received from twitter during application registration. 

But ensure that the server endpoint stated in the request_url, returns a JSON response, with the following keys:

- `success`: `True` on success, `False` on failure
- Any one of the following key
  - `message`: On failure
  - `oauth_token`: On success.

You can read the [README](https://github.com/mdemblani/twitter-login-client/blob/master/README.md) for more information.

**Comment by akshaybhagwat76** [comment]
You mean this not support pure client side authentication for web apps?

**Comment by mdemblani** [comment]
No, unfortunately not. Since, Twitter uses **OAuth1.0** to perform login, a server side extension to the client is required. Also putting up the secret access key in the client JS code, severely risks you at allowing anyone to misuse it, thereby resulting in strict actions by twitter on your application.
